# Generated by Django 3.0.5 on 2020-05-14 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='achieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('info', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumni_image', models.ImageField(upload_to='')),
                ('alumni_name', models.CharField(max_length=100)),
                ('alumni_batch', models.CharField(max_length=100)),
                ('alumni_currentposition', models.CharField(max_length=200)),
                ('alumni_details', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_Name', models.CharField(max_length=100)),
                ('Faculty_Post', models.CharField(max_length=100)),
                ('Faculty_Image', models.ImageField(upload_to='')),
                ('Faculty_Interest', models.CharField(max_length=200)),
                ('Faculty_Phone', models.CharField(max_length=100)),
                ('Faculty_Email', models.CharField(max_length=100)),
                ('Faculty_Type', models.CharField(max_length=100)),
                ('Faculty_Url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('msg', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='homepics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='')),
                ('pictitle', models.CharField(max_length=100)),
                ('picinfo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Library_pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_type', models.CharField(max_length=100)),
                ('pdf_subject', models.CharField(max_length=200)),
                ('pdf_name', models.CharField(max_length=200)),
                ('pdf_doc', models.FileField(upload_to='doc/')),
            ],
        ),
        migrations.CreateModel(
            name='Library_vlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlink_topic', models.CharField(max_length=200)),
                ('vlink_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profilepic', models.ImageField(upload_to='')),
                ('phoneno', models.CharField(max_length=100)),
                ('privateemail', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('skillset', models.CharField(max_length=300)),
                ('github', models.URLField()),
                ('hackerrank', models.URLField()),
                ('codechef', models.URLField()),
                ('private', models.CharField(default='no', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='')),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernames', models.CharField(max_length=50)),
                ('phoneno', models.CharField(max_length=100)),
                ('privateemail', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('skillset', models.CharField(max_length=300)),
                ('github', models.URLField()),
                ('hackerrank', models.URLField()),
                ('codechef', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernames', models.CharField(max_length=50)),
                ('profilepic', models.ImageField(blank=True, upload_to='profile_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernames', models.CharField(max_length=50)),
                ('private', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
