# Generated by Django 3.0.5 on 2020-05-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikhil', '0002_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=50)),
                ('topic_name', models.CharField(max_length=50)),
                ('topic_details', models.CharField(max_length=1000)),
                ('topic_image', models.ImageField(blank=True, upload_to='tutor')),
                ('topic_cpp', models.FileField(upload_to='tutorcpp/')),
            ],
        ),
    ]
